# Generated by Selenium IDE

import time
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys


class TestBaidutest1:
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_baidutest1(self):
        # Test name: baidu_test_1
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("https://www.baidu.com/")
        # 2 | setWindowSize | 738x710 |
        self.driver.set_window_size(738, 710)
        # 3 | click | css=.news-meta-item:nth-child(2) .title-content-title |
        self.vars["window_handles"] = self.driver.window_handles
        # 4 | storeWindowHandle | root |
        # self.driver.find_element(By.CSS_SELECTOR, ".news-meta-item:nth-child(2) .title-content-title").click()
        # 5 | selectWindow | handle=${win315} |
        self.vars["win315"] = self.wait_for_window(2000)
        # 6 | selectWindow | handle=${root} |
        self.vars["root"] = self.driver.current_window_handle
        # 7 | click | id=kw |
        self.driver.switch_to.window(self.vars["win315"])
        # 8 | runScript | window.scrollTo(0,0) |
        self.driver.switch_to.window(self.vars["root"])
        # 9 | type | id=kw | 测试啦
        self.driver.find_element(By.ID, "kw").click()
        # 10 | sendKeys | id=kw | ${KEY_ENTER}
        self.driver.execute_script("window.scrollTo(0,0)")
        # 11 | click | linkText=嫦娥五号完成样品在轨转移 |
        self.driver.find_element(By.ID, "kw").send_keys("测试啦")
        # 12 | selectWindow | handle=${win5386} |
        self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
        # 13 | click | id=kw |
        self.vars["window_handles"] = self.driver.window_handles
        # 14 | click | css=.s_form_wrapper |
        self.driver.find_element(By.PARTIAL_LINK_TEXT, "嫦娥").click()
        # 15 | type | id=kw | 不知道
        self.vars["win5386"] = self.wait_for_window(2000)
        # 16 | sendKeys | id=kw | ${KEY_ENTER}
        self.driver.switch_to.window(self.vars["win5386"])
        # 17 | click | linkText=不知道在线试听_高音质歌曲_网易云音乐 |
        self.driver.find_element(By.ID, "kw").click()
        # 18 | selectWindow | handle=${win9541} |
        self.driver.find_element(By.CSS_SELECTOR, ".s_form_wrapper").click()
        # 19 | close |  |
        self.driver.find_element(By.ID, "kw").send_keys("不知道")
        # 20 | selectWindow | handle=${win5386} |
        self.driver.find_element(By.ID, "kw").send_keys(Keys.ENTER)
        # 21 | selectWindow | handle=${win315} |
        self.vars["window_handles"] = self.driver.window_handles
        # 22 | close |  |
        self.driver.find_element(By.LINK_TEXT, "不知道在线试听_高音质歌曲_网易云音乐").click()
        # 23 | selectWindow | handle=${win5386} |
        self.vars["win9541"] = self.wait_for_window(2000)
        # 24 | close |  |
        self.driver.switch_to.window(self.vars["win9541"])
        # 25 | selectWindow | handle=${root} |
        self.driver.close()
        # 26 | close |  |
        self.driver.switch_to.window(self.vars["win5386"])
        self.driver.switch_to.window(self.vars["win315"])
        self.driver.close()
        self.driver.switch_to.window(self.vars["win5386"])
        self.driver.close()
        self.driver.switch_to.window(self.vars["root"])
        self.driver.close()
  
